import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import { Pacifico } from "next/font/google";
import "./globals.css";

// Configure Pacifico font from Google Fonts
const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
  // Recommended to add viewport for responsive design (Next.js 13+ automatically adds it)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en" 
      suppressHydrationWarning={true}
      className={`${GeistSans.variable} ${GeistMono.variable} ${pacifico.variable}`}
    >
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}